### ISSUE TITLE
niceties with multiple end dates

### ISSUE THREAD

**Issue by xtrntr** [mjec/rc-niceties#9] opened 2016-09-28 01:59 UTC
this probably needs to be weeded out manually

**Comment by jasonaowen** [comment] 2021-03-10 22:45
I believe this is the same problem described by #10, and there's been more of a conversation in that issue.

@xtrntr if that is not what you meant, please re-open this!

**Comment by jasonaowen** [comment] 2021-03-10 22:45
Duplicate of #10

**Closed by jasonaowen** 2021-03-10 22:45 UTC
